global using System.Reflection;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using Microsoft.Extensions.DependencyInjection;
global using System.Collections.ObjectModel;

global using Backend.Infrastructure.Clients.Services;
global using MauiUI.Configurations;
global using Backend.Models;
global using Backend.Models.Settings;
global using Backend.Infrastructure.Interfaces.Services;
global using MauiUI.Clients;
global using MauiUI.Pages;
global using MauiUI.Components;
global using Backend.Infrastructure.Constants;
global using Backend.Models.Common;
